# Generated by Django 2.0.2 on 2018-02-22 04:02

from django.db import migrations, models
import triptailor.models


class Migration(migrations.Migration):

    dependencies = [
        ('triptailor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.FileField(null=True, upload_to=triptailor.models.user_directory_pofile_pic),
        ),
    ]
