# Generated by Django 2.0.2 on 2018-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptailor', '0002_user_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
